package csci240.prinCad.ui;

import javafx.scene.control.Menu;
import javafx.collections.ObservableList;
import javafx.scene.Node;

/** MenuManager Interface:
 * classify all menu factories under one object for easy group control.
 * @author dnglokpor
 */
public interface MenuManager {
	
	/**
	 * make the File menu as predefined javafx Menu and its options and MenuItem objects.
	 * @return a reference to the created menu object created.
	 */
	Menu buildMenu(); // instantiate self
	/**
	 * adds the menu edit menu options to a specific menu bar..
	 * @param nodes points where to attach the menu items. Must be generated by the canvas.
	 */
	void addButtonsToBar(ObservableList<Node> nodes);
}
